### ISSUE TITLE
Tracking issues with non-relative (absolute) URLs

### ISSUE THREAD

**Issue by drummerboy46** [nathanwoulfe/PieMan#11]
If I set useDomainPrefixes=true in the umbracoSettings.config or set a root node culture/hostname in the backoffice. Umbraco publishes absolute URLs. Is there any easy way to tweak the code so that in this scenario, a relative URL is still sent to GA for analysis. Otherwise no results are found.

**Comment by nathanwoulfe** [comment]
I've updated the editor controller to correct this - haven't done a version release, but you can replace both the controller and view in app_plugins and it should be sweet.

**Comment by nathanwoulfe** [comment]
Corrected in v1.0.3
