### ISSUE TITLE
Date range picker?

### ISSUE THREAD

**Issue by drummerboy46** [nathanwoulfe/PieMan#13]
Could we have a date range rather then just the last month? I think this would add a little more flexibility.

**Comment by pmgower** [comment]
I agree, @drummerboy46.  @nathanwoulfe are you still actively maintaining this plugin?

**Comment by nathanwoulfe** [comment]
It's not exactly obvious in the UI, but the 28 day range is an editable value - can be any number of days. 

Working on v2 now.

**Comment by pmgower** [comment]
@nathanwoulfe so would this be by changing the `$scope.dateSpan` value in **line 19** of the [PieMan.editorController.js](https://github.com/nathanwoulfe/PieMan/blob/6185c102a690eaf4074d50b0b3e34d4f11bcb247/PieMan/App_Plugins/Pieman/Backoffice/controllers/PieMan.editorController.js) file?

**Comment by nathanwoulfe** [comment]
That would do it. It's user-editable too though, the displayed value in the UI is an input, so can be changed to any number of days before submitting the request. 

Thinking I might change that up to be a pair of datepickers, so users can choose any date range.

**Comment by pmgower** [comment]
Cool.  We've had some people request being able to change that value to something like 90 days.  Sounds like that'll just be a training issue. =)
