### ISSUE TITLE
Unable to parse filter 'ga:pagePath=='

### ISSUE THREAD

**Issue by bjarnef** [nathanwoulfe/PieMan#3]
If I start the analytics on a subpage I get this error https://github.com/nathanwoulfe/PieMan/issues/2

but at "home" node (relative url "/") it returns the following errors, e.g.:

```
http://localhost:14416/umbraco/backoffice/pieman/analyticsapi/getviewsdatapoints?dateSpan=28&filter=ga:pagePath%3D%3D&profile=34121408 500 (Internal Server error)
```

![image](https://cloud.githubusercontent.com/assets/2919859/8865267/fc7172b4-31ac-11e5-9116-a1d7466bae55.png)

I returns this response:

```
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>Unable to parse filter 'ga:pagePath=='</ExceptionMessage>
<ExceptionType>System.Exception</ExceptionType>
<StackTrace>   at Skybrud.Social.Google.Analytics.Objects.AnalyticsFilterOptions.Parse(String str)   at Skybrud.Social.Google.Analytics.Objects.AnalyticsFilterOptions.op_Implicit(String str)   at PieMan.Controllers.AnalyticsApiController.GetViewsDatapoints(String profile, String DateSpan, String Filter)   at lambda_method(Closure , Object , Object[] )   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.&lt;>c__DisplayClass13.&lt;GetExecutor>b__c(Object instance, Object[] methodParameters)   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.&lt;>c__DisplayClass5.&lt;ExecuteAsync>b__4()   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)</StackTrace>
</Error>
```

Tested with PieMan v0.3.0 and Umbraco 7.2.7

Maybe display an error message in case something went wrong and the data couldn't be fetched from the server, like this used if a property is mandatory.

```
<div ng-show="errorMsg != ''" class="alert alert-error property-error ng-binding" property="property" style="display: none;"></div>
```

If you want you could also display a processbar like this. (you could place it just abobe pieman-wrapper div)

```
<div class="umb-loader-wrapper" ng-show="hasError"><div class=" umb-loader"></div></div>
```

and maybe add this addition if you want the progressbar to left/right.

```
.pieman-editor .umb-loader-wrapper {
  margin-left: -20px;
  margin-right: -20px;
}
```

**Comment by nathanwoulfe** [comment]
Thanks Bjarne - I think I need to find a more robust parameter to identify the current page. Path doesn't appear to work consistently.

Definitely need to improve error handling/reporting

**Comment by nathanwoulfe** [comment]
@bjarnef Home node issue is corrected in v0.4.0 - it's up on our now.

Not sure why you're seeing the other issue on sub-pages. Is the page url display on the general properties tab the same as the publically accessible url for the page? Wondering if there's a discrepancy between the URL I'm sending to the Analytics API and the actual page URL.

**Comment by bjarnef** [comment]
@nathanwoulfe thanks for the fix. I now see data for root page and I don't see the other issue for subpages as I did before.

The reason why I don't see analytics data for subpages is because I am using an Google Analytics account tracking data from www.bjarnefyrstenborg.dk - so locally when I check for path "/explore/our-umbraco" in Fanoe starterkit, of course if haven't any data for such a page in my Analytics account.

However I wonder why I don't see the pie chart for "Device category"?

![image](https://cloud.githubusercontent.com/assets/2919859/8872693/acdba460-31ff-11e5-9af9-3123227616b3.png)

If I disable "tablet" I do see the pie.

![image](https://cloud.githubusercontent.com/assets/2919859/8872716/e11dc51e-31ff-11e5-842a-67cfe7050dd4.png)

It looks like this for the part 28 days in Google Analytics.

![image](https://cloud.githubusercontent.com/assets/2919859/8873164/23e1a196-3204-11e5-9c61-434be9feac2b.png)

**Comment by nathanwoulfe** [comment]
Relative root path issue has been rectified. Will create a new issue for the tablet data - have a feeling it's a rounding error. Maybe.
