### ISSUE TITLE
Localization of text

### ISSUE THREAD

**Issue by bjarnef** [nathanwoulfe/PieMan#4]
Since the package is located in the content section and is intended for editors is should have localized text, e.g. for "Show analytics for previous", "days" etc.

You could see how we have localized most of the text in the Analytics package https://github.com/warrenbuckley/Analytics

**Comment by nathanwoulfe** [comment]
Thanks Bjarne, will do.

**Comment by MarcStoecker** [comment]
Totally agree, would be awesome if you could allow localization.

**Comment by nathanwoulfe** [comment]
@bjarnef @esn303 - shouldn't be too difficult, looks like the Merchello team found a useful solution

**Comment by MarcStoecker** [comment]
Good news! Thanks for looking into it. :)

**Comment by nathanwoulfe** [comment]
Localization is in version 0.5.0. Only did Danish and English for starters, will work on adding more when I have time.

**Comment by bjarnef** [comment]
@nathanwoulfe something you may consider in https://github.com/nathanwoulfe/PieMan/blob/master/App_Plugins/Pieman/auth/OAuthCallback.aspx.cs is to use TextService instead of ui.Text which is deprecated: https://twitter.com/Shazwazza/status/613986522631667712 .. not sure if it handle fallback for older versions of Umbraco 7.

**Comment by nathanwoulfe** [comment]
I wanted to fix the deprecration warnings, and was digging in LocationService but couldn't find it. That would be why - it's in TextService.
