### ISSUE TITLE
Error getting profiles from account

### ISSUE THREAD

**Issue by pgregorynz** [nathanwoulfe/PieMan#6]
Hi Nathan

I have Umbraco 7.2.8 and I'm getting a 500 error when it loads the slidein dialog when it tries to get Analytics profiles from my account.  When inspecting its the following call that failing

http://localhost:50710/umbraco/backoffice/pieman/analyticsapi/getprofilesfromaccount?accountId=null

I suspect because its passing Null...   I have authorised the account and it seemed to work.  How do I clear that authoirisation?

**Comment by pgregorynz** [comment]
oh and to add to this...  The accounts dropdown has 6 blank items that I assume match up with my 6 different analtytics properties

**Comment by nathanwoulfe** [comment]
Hi Peter

That's no good. If you have a look at the data type in the developer section, does it show the populated config values? Should display a JSON string with your analytics credentials, assuming the oAuth flow was successful. 

N

**Comment by pgregorynz** [comment]
Actually think i figured it out.  I have Merchello installed and I think its got a JsonFormater in it that converts everything to CamelCase and it effects all packages.. Im looking into it further.
