### ISSUE TITLE
Reason for selecting profile in content section

### ISSUE THREAD

**Issue by bjarnef** [nathanwoulfe/PieMan#7]
I have thought about if there is a reason, why the auth in the dialog is located in the content section and not in the property editor config in developer section?

I am not sure if editors need to change this? I mean, often you will only configurate it once. Usually I think an admin will choose this anyway?

If any special reason for it to be located in content section, then maybe only make the cog visible to admin users?

**Comment by akeilox** [comment]
I had the same concern, as some (new) users caught fiddling with it.
It would be great if this can be set in the developer section or alternatively like @bjarnef said only allow it for admins.

There are times, when multiple domain properties are in the analytics account, and in current form any user gets to fiddle with them which is not desirable.

**Comment by nathanwoulfe** [comment]
@bjarnef - apologies for the slowness, thought I'd addressed this.

@akeilox - absolutely valid concern. The use-case when I was developing it was the inverse - a single domain with multiple views of the same property, so it made sense to allow changes to the settings from within the content section. I'll make it admin-only.

Planning to - when time permits - merge this project with the Analytics for Umbraco package.

**Comment by nathanwoulfe** [comment]
I've just updated the editor controller and view to set the button state based on user type - I'll do a proper release soon(ish), but for now you can always just replace these two files in /App_plugins/Pieman.

**Comment by akeilox** [comment]
Great to hear to Nathan. Much appreciated.
Looking forward to the next release.

**Comment by nathanwoulfe** [comment]
v1.0.3 is up now, settings only displayed for admin user type.
