### ISSUE TITLE
Using Pieman to show multiple accounts

### ISSUE THREAD

**Issue by iahdevelop** [nathanwoulfe/PieMan#9]
Hello Nathan 
I have a multi-site Umbraco installation and each website has its own Google Analytics account. So is possible to use Pieman to show different account for each website?

Best,

**Comment by nathanwoulfe** [comment]
Hi Ibrahim

I haven't tried it, but I think it would work if you create a data type for each site, using the PieMan editor. You'd then need to authenticate each instance against the correct account. Like I said, haven't tried it, but it should work as the auth info is scoped to the data type.
